# Generated by Django 5.0.4 on 2024-04-08 20:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aktualnosci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True)),
                ('tytul', models.CharField(max_length=255)),
                ('opis', ckeditor.fields.RichTextField(max_length=90000)),
                ('grafika', models.ImageField(upload_to='news/')),
            ],
        ),
    ]
