# Generated by Django 5.0.4 on 2024-04-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktualnosci',
            name='grafika',
            field=models.ImageField(blank=True, null=True, upload_to='news/'),
        ),
    ]
