# Generated by Django 5.0.4 on 2024-04-22 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_aktualnosci_grafika'),
    ]

    operations = [
        migrations.CreateModel(
            name='Czlonkowie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255)),
                ('miasto', models.CharField(max_length=255)),
                ('ulica', models.CharField(max_length=255)),
                ('kod', models.CharField(max_length=10)),
                ('telefon', models.CharField(max_length=20)),
                ('strona', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo_www/')),
                ('baner', models.ImageField(blank=True, null=True, upload_to='logo_www/')),
            ],
        ),
    ]
