# Generated by Django 5.0.4 on 2024-04-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_czlonkowie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='czlonkowie',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='czlonkowie',
            name='kod',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='czlonkowie',
            name='strona',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='czlonkowie',
            name='telefon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
