# Generated by Django 5.0.4 on 2024-04-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_czlonkowie_email_alter_czlonkowie_kod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='czlonkowie',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='czlonkowie',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='czlonkowie',
            name='twitter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
