# Generated by Django 5.0.4 on 2024-04-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_czlonkowie_facebook_czlonkowie_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='czlonkowie',
            name='czwartek',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='czlonkowie',
            name='piatek',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='czlonkowie',
            name='poniedzialek',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='czlonkowie',
            name='sroda',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='czlonkowie',
            name='wtorek',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
