# Generated by Django 5.0.4 on 2024-04-25 10:48

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_czlonkowie_czwartek_czlonkowie_piatek_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktualnosci',
            name='obraz',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
