# Generated by Django 5.0.4 on 2024-04-26 08:27

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_aktualnosci_obraz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aktualnosci',
            name='obraz',
        ),
        migrations.AlterField(
            model_name='aktualnosci',
            name='opis',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=90000),
        ),
    ]
